### ISSUE TITLE
Issue with timeline.today() on `timezones` branch

### ISSUE THREAD

**Issue by thehammeredone** [ics-py/ics-py#292]
I am at commit 18235b2, and I noticed that calling `timeline.today()` wasn't working. I got the error:

```
Traceback (most recent call last):                                                                                                                                                            
  File "/home/hammer/bin/icsscript", line 91, in <module>                                                                                                                                     
    printTodos()                                                                                                                                                                              
  File "/home/hammer/bin/icsscript", line 57, in printTodos                                                                                                                                   
    for e in c.timeline.today():                                                                                                                                                              
  File "/home/hammer/git/external/ics-py/src/ics/timeline.py", line 144, in today                                                                                                             
    return self.on(date.today(), strict=strict)                                                                                                                                               
  File "/home/hammer/git/external/ics-py/src/ics/timeline.py", line 132, in on                                                                                                                
    query = self.__normalize_timespan(begin, end)                                                                                                                                             
  File "/home/hammer/git/external/ics-py/src/ics/timeline.py", line 45, in __normalize_timespan                                                                                                   timespan = Timespan(ensure_datetime(start), ensure_datetime(stop))                                                                                                                        
  File "<attrs generated init ics.timespan.Timespan>", line 11, in __init__                                                                                                                   
  File "/home/hammer/git/external/ics-py/src/ics/timespan.py", line 86, in __attrs_post_init__                                                                                                
    self.validate()                                                                                                                                                                           
  File "/home/hammer/git/external/ics-py/src/ics/timespan.py", line 146, in validate                                                                                                          
    raise ValueError("begin time must be before " + self._end_name() + " time")                                                                                                               
ValueError: begin time must be before end time                                                                                                                                                
```

Turns out, on line 139 of timeline.py, timeline.today() calls `self.on()` with `date.today()` as the argument. It needs to use `datetime.today()` as that argument for the `floor...` and `ceil...` calls within the `on()` function to work properly.

Hope that helps!

I'm actually going to install the timezones branch as the working `ics` library on my computer, in order to handle the folks in other timezones creating meetings, and messing with my workflow!

**Comment by N-Coder** [comment]
I included a fix for this in #293, could you check whether everything works now? I'm actually kind of intereseted in your use-case as I spent quite some time trying to get Timezones useable. Could you elaborate or would you even be willing to help putting the main parts of your use-case into unit-tests?

**Comment by thevickypedia** [comment]
@N-Coder I have the exact same concern with the timezones.
People from other timezones create meeting invites and when I use the latest version of `ics` I'm not able to get the timezone information.

Sample code:
```python
from ics import Calendar
import requests
from modules.models import models
env = models.env
cal = Calendar(requests.get(env.url).text)
events = list(cal.timeline.today())
for event in events:
    print(f"You have a meeting at {event.begin.strftime('%I:%M %p')} {env.title}! {event.name}.")
```
`event.begin` doesn't have anything that can get me the timezone the meeting was set in.

**Comment by N-Coder** [comment]
Could you please give us a minimal reproducible example, i.e. one also including some exemplary ICS data that causes the issue and not using any unrelated modules. Which exact version of ics.py are you using?
Also I'm not quite sure what you mean with "event.begin doesn't have anything that can get me the timezone the meeting was set in". Do you get the same exception that was reported in this issue?

**Comment by thevickypedia** [comment]
Forgive me for the lack of information. I'm using the latest version from pypi `0.7`
My question is as simple as "How can I get the timezone of an event"

**Comment by thevickypedia** [comment]
Sample event. I'm in central timezone and the person who sent this invite is in pacific timezone. So, timestamp on this event is 8 PM but for me it is actually at 10 PM. So I'm looking for the event's timezone information to convert it to local timezone.

```
BEGIN:VEVENT
PRIORITY:5
SEQUENCE:2
X-MICROSOFT-CDO-APPT-SEQUENCE:2
X-MICROSOFT-CDO-BUSYSTATUS:TENTATIVE
X-MICROSOFT-CDO-INTENDEDSTATUS:BUSY
X-MICROSOFT-CDO-ALLDAYEVENT:FALSE
X-MICROSOFT-CDO-IMPORTANCE:1
X-MICROSOFT-CDO-INSTTYPE:0
X-MICROSOFT-DONOTFORWARDMEETING:FALSE
X-MICROSOFT-DISALLOW-COUNTER:FALSE
CLASS:PUBLIC
DTSTAMP:20220330T224124Z
DESCRIPTION:EVENT DESCRIPTION
DTEND:20220330T204500Z
LOCATION:https://example.com
DTSTART:20220330T200000Z
STATUS:CONFIRMED
SUMMARY:Sample meeting
TRANSP:OPAQUE
UID:040000008200E00074C5B7101A82E00800000000258DD8F4082DD80100000000000000001000000035CD31669C19E048BA15EE540727884D
END:VEVENT
```

**Comment by N-Coder** [comment]
The dates in your ics file are specified in UTC instead of using any regional timezone like US central or pacific:
> The date with UTC time, or absolute time, is identified by a LATIN CAPITAL LETTER Z suffix character, the UTC designator, appended to the time value.  For example, the following represents January 19, 1998, at 0700 UTC: 19980119T070000Z

This information should also be stored with the begin and end time of the event. v0.7 uses [arrow datetime](https://arrow.readthedocs.io/en/latest/index.html#properties) objects for this, which sometimes have issues with local timezones, but that shouldn't affect you UTC timestamps (see #222 for details). This is why the upcoming v0.8 on the master branch replaced arrow with the more stable builtin `datetime` objects - maybe checkout that new version if you have further issues. Otherwise you can open a new issue.

**Comment by thevickypedia** [comment]
Sure, I will take a peek at it. Thank you so much.
