### ISSUE TITLE
tatsu.exceptions.FailedExpectingEndOfText with outlook

### ISSUE THREAD

**Issue by vetsolution** [ics-py/ics-py#298]
Hello,
I have a trouble using the library.
But tatsu trigger a tatsu.exceptions.FailedExpectingEndOfText on the fields DESCRIPTION

Any idea how to debug the issue or mitigate it ?
I use ics==0.7 and tatsu==5.6.1

Regards

**Comment by N-Coder** [comment]
Probably something with your input file

BR

**Comment by vetsolution** [comment]
Yes it should come from the input file, but it come directly from outlook 365
No problem with an google calendar.
My question is how to debug what going on with this specific import ;)

**Comment by N-Coder** [comment]
Check this out:
https://stackoverflow.com/help/minimal-reproducible-example
Without (the problematic lines of) your input file, the full stack trace and possibly some code (if you're doing more than `Calendar(open("file.ics"))` it's hard to help you.

**Comment by vetsolution** [comment]
Hello,
I'll try to give as much as details I can, but it's tricky because what's causing the trouble is certainly in the ics file, and I cannot share it because privacy concern.

Here is the full stack trace:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/app/service.py", line 14, in convert
    c = Calendar(requests.get(url).text)
  File "/usr/local/lib/python3.7/site-packages/ics/icalendar.py", line 63, in __init__
    containers = calendar_string_to_containers(imports)
  File "/usr/local/lib/python3.7/site-packages/ics/grammar/parse.py", line 199, in calendar_string_to_containers
    return string_to_container(string)
  File "/usr/local/lib/python3.7/site-packages/ics/grammar/parse.py", line 182, in string_to_container
    return lines_to_container(txt.splitlines())
  File "/usr/local/lib/python3.7/site-packages/ics/grammar/parse.py", line 178, in lines_to_container
    return parse(tokenize_line(unfold_lines(lines)))
  File "/usr/local/lib/python3.7/site-packages/ics/grammar/parse.py", line 171, in parse
    res.append(Container.parse(line.value, tokenized_lines))
  File "/usr/local/lib/python3.7/site-packages/ics/grammar/parse.py", line 126, in parse
    items.append(Container.parse(line.value, tokenized_lines))
  File "/usr/local/lib/python3.7/site-packages/ics/grammar/parse.py", line 124, in parse
    for line in tokenized_lines:
  File "/usr/local/lib/python3.7/site-packages/ics/grammar/parse.py", line 164, in tokenize_line
    yield ContentLine.parse(line)
  File "/usr/local/lib/python3.7/site-packages/ics/grammar/parse.py", line 76, in parse
    ast = GRAMMAR.parse(line)
  File "/usr/local/lib/python3.7/site-packages/tatsu/grammars.py", line 1042, in parse
    **kwargs
  File "/usr/local/lib/python3.7/site-packages/tatsu/contexts.py", line 226, in parse
    raise self._furthest_exception
  File "/usr/local/lib/python3.7/site-packages/tatsu/contexts.py", line 218, in parse
    result = rule()
  File "/usr/local/lib/python3.7/site-packages/tatsu/grammars.py", line 782, in parse
    result = self._parse_rhs(ctx, self.exp)
  File "/usr/local/lib/python3.7/site-packages/tatsu/grammars.py", line 790, in _parse_rhs
    result = ctx._call(ruleinfo)
  File "/usr/local/lib/python3.7/site-packages/tatsu/contexts.py", line 519, in _call
    result = self._recursive_call(ruleinfo)
  File "/usr/local/lib/python3.7/site-packages/tatsu/contexts.py", line 548, in _recursive_call
    return self._invoke_rule(ruleinfo, self.memokey)
  File "/usr/local/lib/python3.7/site-packages/tatsu/contexts.py", line 595, in _invoke_rule
    ruleinfo.impl(self)
  File "/usr/local/lib/python3.7/site-packages/tatsu/grammars.py", line 390, in parse
    ctx.last_node = [s.parse(ctx) for s in self.sequence]
  File "/usr/local/lib/python3.7/site-packages/tatsu/grammars.py", line 390, in <listcomp>
    ctx.last_node = [s.parse(ctx) for s in self.sequence]
  File "/usr/local/lib/python3.7/site-packages/tatsu/grammars.py", line 227, in parse
    ctx._check_eof()
  File "/usr/local/lib/python3.7/site-packages/tatsu/contexts.py", line 664, in _check_eof
    self._error('Expecting end of text', exclass=FailedExpectingEndOfText)
  File "/usr/local/lib/python3.7/site-packages/tatsu/contexts.py", line 453, in _error
    raise self._make_exception(item, exclass=exclass)
tatsu.exceptions.FailedExpectingEndOfText: (1:333) Expecting end of text :
DESCRIPTION:Dear members and friends\,\n\nHappy new year! (other text removed for privacy)
```
This is the code runing in a flask microservice
```
from flask import Flask,request 
import json, requests
from ics import Calendar
from datetime import timedelta, datetime, timezone
app = Flask(__name__)


@app.route('/convert')
def convert():
	url = request.args.get('url', '')
	end = datetime.now(timezone.utc)-timedelta(weeks=5)
	c = Calendar(requests.get(url).text)    # we just downloads the ics from an url and parse it with your lib
	print(end, list(c.events)[0].begin)
	res = [
			{
                                        "start":e.begin.strftime("%Y-%m-%d %H:%M:%S"),
                                        "end":e.end.strftime("%Y-%m-%d %H:%M:%S"),
                                        "summary":e.name,
                                        "uid":e.uid,
                                        "description":e.description,
                          } for e in c.events if e.begin> end
	]
	return json.dumps(res)

```
This work well with google calendar, but doesn't with Outlook 365.
I know that without the problematic file is hard to give a solution. But, I was thinking that this exception was quite common and that you have some trick to find out what is wrong in the ics file ;) (ex: utf-8 bad char, some weird stuff coming from windows IIS encoding, ...)

I already try to convert the text in ascii by removing all the special char but it doesn't help (with  text.encode("ascii", ignore=True).decode("ascii") ), and I have no other idea of what else can I do :s

Is there a way to split the events in the ics before parsing it?
Because here an error in one event avoid to import all the events. But, if I can parse event by event I can catch the parsing exception and just ignore what's not importable.

Thanks for you help ;)

Regards

**Comment by N-Coder** [comment]
You can try validating the file here: https://icalendar.org/validator.html
Otherwise, maybe check out the current `main` branch for a (pre-alpha) version with a much more resilient parser (that could, unlike the current one, also do the line-by-line parsing you are asking for).
Unfortunately, I haven't seen the exception before and have no magic trick at hand to find out what's wrong with your file without seeing the content that's causing the problem.
You can try opening the file with a text editor and stripping it down until you have a publishable, minimal file that still causes the same problem and posting that here.

**Comment by vetsolution** [comment]
So,
https://icalendar.org/validator.html report no issue. But I found the problem.

I several events they were some unprintable characters (\x18,\x19,\x13) [https://condor.depaul.edu/sjost/lsp121/documents/ascii-npr.htm](https://condor.depaul.edu/sjost/lsp121/documents/ascii-npr.htm)

I was seeing it gedit. But, I was thinking that ` with text.encode("ascii", ignore=True).decode("ascii")   ` would filter those weird characters, but they are ascii chars indeed.

Maybe a sanitization of the user input with something like below could increase the robustness of the lib.

```
import requests, string
url    = "https://.../"
raw    = requests.get(url).text)
clean  = ''.join(filter(lambda x: x in string.printable, raw )
c      = Calendar(clean) 
```

Thank you for your help

**Comment by N-Coder** [comment]
The new parser should be able to also handle those, so I'm closing this, but feel free to try out the new parser from the `main` branch yourself!
